Stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_friends/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
 ]

profile_page/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
]

tp1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import profile_page.urls as profile_page
import update_status.urls as update_status
import app_friends.urls as app_friends
import Stats.urls as Stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status,namespace='update-status')),
    url(r'^friends/', include(app_friends,namespace='friends')),
    url(r'^$', RedirectView.as_view(url="/update-status/",permanent="true"), name='redirect_landing_page'),
    url(r'^profile-page/', include(profile_page,namespace='profile-page')),
    url(r'^Stats/', include(Stats,namespace='Stats')),
]

update_status/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

Stats/models.py
from django.db import models

# Create your models here.

app_friends/models.py
from django.db import models

class Friends(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

profile_page/models.py
from django.db import models

class Profiledata(models.Model):
	name = models.CharField(max_length=250)
	Birthday = models.CharField(max_length=20)
	Gender = models.CharField(max_length=200)
	expertise = models.TextField(max_length=200)
	Description = models.CharField(max_length=200)
	Email = models.CharField(max_length=200)
	profil_pict = models.URLField(default="https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg")

update_status/models.py
from django.db import models

# Create your models here.

class StatusModel(models.Model):
    name = models.CharField(max_length=50,default='Hepzibah Smith')
    date = models.DateTimeField(auto_now_add=True)
    status = models.TextField()

app_friends/forms.py
from django import forms

class Add_Forms(forms.Form):
	error_messages = {
		'required': 'Mohon diisi form ini',
		'invalid': 'Isi input dengan URL',
	}
	attrs_name = {
		'class': 'form-control',
		'placeholder': 'Enter your friend(s) name here'
	}
	attrs_url = {
		'class': 'form-control',
		'placeholder': 'Enter your friend(s) URL here'
	}

	name = forms.CharField(label='Nama', required=True, max_length=30, widget=forms.TextInput(attrs=attrs_name))
	url = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=attrs_url))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    attrs = {
        'class': 'form-control',
        'placeholder': 'What is on your mind?'
    }
    status = forms.CharField(widget=forms.Textarea(attrs=attrs))

Stats/views.py
from django.shortcuts import render
#from .models import StatusModel

# Create your views here.
from django.shortcuts import render
from update_status.models import StatusModel
#from update_status.views import index
from app_friends.models import Friends

#name = 'PPW-E Group 5 Team'
#content = 'This is a testing web. A really simple one even. PPW GANBARU MINNA!'
# Create your views here.
profile_name = 'Hepzibah Smith' #TODO implement your name here
def index(request):
    response = {'name':profile_name,'status_count':StatusModel.objects.all().count(), 'friends_count': Friends.objects.all().count(),'status_model':StatusModel.objects.last()}
    return render(request, 'header.html', response)

app_friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Forms
from .models import Friends

# Create your views here.
response = {'author': "KELOMPOK 5 PPW-E"} #TODO Implement yourname
def index(request):
	friends = Friends.objects.all()
	html = 'app_friends.html'
	#TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
	response['friends'] = friends
	response['add_forms'] = Add_Forms
	return render(request, html, response)
	
def add_friend(request):
	form = Add_Forms(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friends(name=response['name'], url=response['url'])
		friend.save()
	return HttpResponseRedirect('/friends/')

profile_page/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Profiledata

# Create your views here.
profile_name = 'Hepzibah Smith' #TODO implement your name here
birth_date = date(1998,1,1) #TODO implement your birthday
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Female' #TODO implement your gender
email = 'hello@smith.com' #TODO implement your email
desc_profile = "Antique Expert. Experience as marketer for 10 years"
expert = "Marketer || Collector || Public Speaking"
picture = "https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg"
profil = Profiledata(name = profile_name, Birthday = birthdate, Gender= gender, Email = email, Description=desc_profile, expertise=expert, profil_pict= picture)

def index (request):
	response= {'name': profil.name, 'birthyear': profil.Birthday, 'gender': profil.Gender, 'expertise': profil.expertise, 'description': profil.Description, 'email': profil.Email, 'picture_user': profil.profil_pict}
	return render(request, 'profile_page.html', response)

update_status/views.py
from django.shortcuts import render
from .models import StatusModel
from .forms import Status_Form
from Stats.views import profile_name

# Create your views here.
response = {}
#latest=history.last() 
def index(request):
    form = Status_Form(request.POST)
    html = 'update-status.html'
    if request.method == 'POST':
        if form.is_valid():
            response['name']=profile_name
            response['status'] = form.cleaned_data.get('status')
            post = StatusModel(status=response['status'])
            post.save()
            history = StatusModel.objects.all().order_by('date').reverse()
            form = Status_Form()
            response['form']=form
            response['history']=history
            #response['latest']= latest
            #response['name']=name
            return render(request,html,response)

    else:
        response['name']=profile_name
        form = Status_Form()
        response['form'] = form
        history = StatusModel.objects.all().order_by('date').reverse()
        response['history']=history
        #response['latest']= latest
        return render(request, html, response)

Stats/templates/header.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}
<!--<h1 style="font-size: 30px;font-family:OCR A Std;color: #8b2252;text-shadow: 2px 2px #ee82ee;background-color: #bbffff">Statistik</h1>
<hr/>-->

<body>
    <h2 class='container' style="font-size: 30px;font-family:OCR A Std;color: 	#d9ffcc"><b>Statistic</b>
    </h2>
    <h1 style="font-size: 40px;color: #ccff99"><img src='https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg' style="float:middle;width: 10%;height: 10%; border-radius: 50%; align-items: left; margin-left: 35%">{{name}}</h1>
<div>
    <p style="text-align: center ; font: bold 30px/30px Arial; color: #f2f2f2">Friends : {{friends_count}} people</p>
    <p style="text-align: center; font: bold 30px/30px Arial;color: #f2f2f2"> Feed : {{status_count}} post</p>
</div>   
  <ul class="nav navbar-nav" style="background-color: #b3ffe6">
  <div class='container'>
    <p style="text-align: center ; font: bold 30px/30px Arial;center; color: 	#339966; text-decoration: underline; text-decoration-color: #003300">Latest Post</p>
    <p style="font-family:OCR A Std;font-size: 30px; color: #00b300"><img src='https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg' style="float:left;width: 10%;height: 10%; border-radius: 50%; align-items: left" width="20" height="20">{{status_model.name}}</p>
  	<p style="font-size: 20px; color: #0099ff">{{status_model.status}}</p> <!--???????-->
  	<p style="font-size: 20px; color: #0099ff">{{status_model.date}}</p>
 </div>
 </div>    
</body>
{% endblock %}

app_friends/templates/app_friends.html
{% extends "layout/base.html" %}

{% block content %}
 <title>Status</title>
<h1 class="container" style="font-family:OCR A Std;font-size: 30px;color: 	#d9ffcc">Add Friends</h1>
<br>
<section name="form" class="container">
	
	<form id="form" class="form-horizontal" method="POST" action="{% url 'friends:add_friend' %}">
		{% csrf_token %}
		{% for input in add_forms %}
			<div class="form-group">
				<label class="control-label col-sm-2" for="{{input.name}}"> {{input.label}} </label>
				<div class="col-sm-12">{{input}}</div>
			</div>
		{% endfor %}
		<br>
		<div align="right">
			<button type="submit" class="btn btn-default">Add Friend</button>
		</div>
	</form>
</section>
<br>
<ul class="nav navbar-nav">
<section name="table" class="container">
	<table class="table" border="0">
		<thead>
			<th>List Friend</th>
			<th></th>
			<th></th>
		</thead>
		<tbody>
			<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
			{% for i in friends %}
				<td style="font-size: 20px"> {{i.name}} </td>
				<td style="font-size: 20px"><a href="{{i.url}}"> {{i.url}} </a></td>
				<td style="font-size: 20px"><i><small> Added on {{i.created_date.date}} {{i.created_date.time}} </small></i></td>
			</tr>             
			{% endfor %}
		</tbody>
	</table>
</section>
</ul>
{% endblock %}

profile_page/templates/profile_page.html
{% extends "layout/base.html" %}
{% block content %}


<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet "> 
<section name="Profile" style="float: middle">
	<h3 class= 'container' style="font-size: 40;font-family:OCR A Std;color: 	#d9ffcc; margin-top: 1%">
	<b>Profile</b>
	</h3>
</section>
<section name="bio" id="bio">
	<img src="https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg" style="float:middle;width: 30%;height: 30%; border-radius: 50%; align-items: center; margin-left: 35%">
	<div class="profil_profil" id="profil_profil" style="font-family: 'Roboto'">
		<h4 id="user" style="">
			<b>{{ name }}</b>
		</h4>
		<table id="table">
			<tr>
				<th style="width: 35%;color: #d9ffcc">Birth Year</th>
				<td style="color: #f2f2f2">{{ birthyear }}</td>
			</tr>
			<tr>
				<th style="width: 35%;color: #d9ffcc">Gender</th>
				<td style="color: #f2f2f2">{{ gender }}</td>
			</tr>
			<tr>
				<th style="width: 35%;color: #d9ffcc">Expertise</th>
				<td style="color: #f2f2f2">{{ expertise }}</td>
			</tr>
			<tr>
				<th style="width: 35%;color: #d9ffcc">Description</th>
				<td style="color: #f2f2f2">{{ description }}</td>
			</tr>
			<tr>
				<th style="width: 35%;color: #d9ffcc">Email</th>
				<td style="color: #f2f2f2">{{ email }}</td>
			</tr>
		</table>

	
	</div>
</section>	
<style>
	body {
	  min-height: 600px;
	}

	.navbar-static-top {
	  margin-bottom: 19px;
	}

	.nav navbar-nav {
		text-align: center; font: bold 30px/30px Arial
	}

	#bio{
		width: 600px;
		height: 600px;
		margin-left: 30%;
	}
	#table{
		align-items: center;
		height: 40px;
		font-size: 20px;
		width: 600px;
		margin-top: 5%;
	}
	#user{
		text-align: center;
		margin-top: 5%;
		color: #ccff99;
		font-size: 40px;
	}
	@media only screen and (max-width: 767px) {
	  #bio{
	  	width: 250px;
	  	height: 250px;
	  	margin-left: 5%;
	  }
	  #table{
	  	width: 250px;
	  	font-size: 15px;
	  	margin-left: 10%;
	  }
	  #user{
	  	font-size: 20px;
	  }
	  body{
	  	min-height: 400px;
	  }
	}
</style>
<br><br>
{% endblock %}

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet"> 
<head>
    <title>Ling In</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    body{
      background-size: cover;
      background-repeat: no-repeat;
      background-color: teal;
    }
    li a {
        display: block;
        padding: 8px 16px;
        text-decoration: none;
    }

    /* Change the link color on hover */
    li a:hover {
        background-color: #FFCAE3;
        color: #FFFFFF;
    }
    ul{
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      /*background-color: lightblue;*/
    }
</style>
<body>
    
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#" style="font-size: 30px;font-family:Acme;color: #8b2252;text-shadow: 2px 2px #ee82ee" >Ling In</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/update-status/">Status</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/profile-page/">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/friends/">Friends</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/Stats/">Stats</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/partials/footer.html
<p style="text-align: center;">&#169; By Kelompok 5 Kelas PPW E</p>

templates/partials/header.html
<h1 style="font-size: 30px;font-family:OCR A Std;color: #8b2252;text-shadow: 2px 2px #ee82ee;background-color: #bbffff">Statistik</h1>
<hr/>
<body style="background-color: #ffffe6">
    <h1 style="font-size: 30px;font-family:OCR A Std;color: #1a1aff;text-shadow: 2px 2px #ff0000 "><img src='https://image.ibb.co/nCzedw/yuzu.png' width="150" height="150" >{{msg.name}}</h1>
</body>
<nav>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <a style="text-align: left ; font: bold 20px/30px Arial;font-size: 30px;font-family:OCR A Std;color: #8b2252;text-shadow: 2px 2px #ee82ee">Friends : </a>
      </ul>
      <ul class="nav navbar-nav">
        <a style="text-align: left ; font: bold 20px/30px Arial;font-size: 30px;font-family:OCR A Std;color: #8b2252;text-shadow: 2px 2px #ee82ee"> Feed : </a>
        <a style="text-align: right ; font: bold 20px/30px Arial;font-size: 30px;font-family:OCR A Std;text-shadow: 2px 2px #ee82ee"> {{status_count}} post</a>
      </ul>
      <ul class="nav navbar-nav">
        <a style="text-align: right ; font: bold 20px/30px Arial;font-size: 30px;font-family:OCR A Std;color: #8b2252;text-shadow: 2px 2px #ee82ee">Latest Post</a> 
      </ul>
    </div><!--/.nav-collapse -->
  </div>
  
</html>

update_status/templates/update-status.html
{% extends "layout/base.html" %}
{% block content %}
<div class="container">
	<h1 class="container" style="font-family:OCR A Std;font-size: 30px;color: 	#d9ffcc">Update Status</h1>
    <form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-info">Post</button>
	</form>
	<br>
</div>
<br>
<ul class="nav navbar-nav" style="background-color: #b3ffe6">
<div class="container">
<hr>
<p style="font-family:OCR A Std;font-size: 20px; text-decoration: underline; text-align: center; color: 	#339966; font-weight: bold; font-size: 35px">News Feed</p>
	{% if history %}
	{% for msg in history %}
		<h2 style="font-family:OCR A Std;font-size: 30px; color: #00b300"><img src='https://files.tofugu.com/articles/japanese/2016-04-25-chibi/chibihowto-03.jpg' style="float:left;width: 10%;height: 10%; border-radius: 50%; align-items: left" width="50" height="50">{{name}}</h2>
		<p style="font-size: 20px; color: #0099ff">{{msg.status}}</p>
		<p style="font-size: 20px; color: #0099ff">{{msg.date}}</p>
		<br>
		<hr>
		{% endfor %}
	{% endif %}
</div>
</ul>
{% endblock %}